# Maven
# Build Heloavy Web Application and run tests with Apache Maven.
# Azure DevOps CI/CD Pipeline - Heloavy Pvt. Ltd.
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  displayName: 'Build HeloavyWebApp with Maven'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17.0'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: CopyFiles@2
  displayName: 'Copy WAR artifact'
  inputs:
    Contents: '**/*.war'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Heloavy Build Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'heloavy-drop'
    publishLocation: 'Container'
